In [1]:
import numpy as np

In [2]:
lst =[12,45,65,89]
print(lst)

[12, 45, 65, 89]


In [4]:
arr1= np.array(lst)
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)

[12 45 65 89]
1
(4,)
4


In [10]:
arr2=np.array([[12,43,56,87,90],[11,22,33,44,55],[21,34,87,90,65],[1,2,3,4,5]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2[0,2])
print(arr2[1:3,2:4])

[[12 43 56 87 90]
 [11 22 33 44 55]
 [21 34 87 90 65]
 [ 1  2  3  4  5]]
2
(4, 5)
20
56
[[33 44]
 [87 90]]


In [12]:
arr3= np.array([[[12,43,56,87,90],[11,22,33,44,55]],[[21,34,87,90,65],[1,2,3,4,5]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)

[[[12 43 56 87 90]
  [11 22 33 44 55]]

 [[21 34 87 90 65]
  [ 1  2  3  4  5]]]
3
(2, 2, 5)
20


In [14]:
a= np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [15]:
a= np.arange(24).reshape(4,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [16]:
ls= np.linspace(1,10)
print(ls)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [17]:
ls= np.linspace(1,10,5)
print(ls)

[ 1.    3.25  5.5   7.75 10.  ]


In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
a= np.array([[1,4,7],[3,2,5]])
print(a)

[[1 4 7]
 [3 2 5]]


In [20]:
np.sum(a)

22

In [21]:
np.sum(a,axis=1)

array([12, 10])

In [22]:
np.sum(a,axis=0)

array([ 4,  6, 12])

In [24]:
b= np.array([[1,3,6],[4,8,9]])
print(a)
print(b)

[[1 4 7]
 [3 2 5]]
[[1 3 6]
 [4 8 9]]


In [25]:
np.multiply(a,b)

array([[ 1, 12, 42],
       [12, 16, 45]])

In [26]:
np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [28]:
np.matmul(a,b.T)

array([[55, 99],
       [39, 73]])

In [29]:
a

array([[1, 4, 7],
       [3, 2, 5]])

In [30]:
np.mean(a)

3.6666666666666665

In [31]:
np.median(a)

3.5

In [32]:
np.std(a)

1.9720265943665387

In [33]:
np.var(a)

3.8888888888888893

In [34]:
np.random.normal(50,13,50)

array([40.12083856, 49.84424848, 68.86278385, 54.93745364, 58.55367991,
       45.72356869, 29.32812198, 46.47151998, 74.72207865, 32.77152669,
       63.89796138, 47.60724559, 62.02740987, 65.59803854, 72.5982146 ,
       49.75530766, 38.6991667 , 46.87124845, 60.53183386, 38.21397323,
       53.66963057, 55.76917865, 62.88266119, 58.36331936, 50.36119759,
       40.24034056, 42.84534572, 52.70998982, 68.60680556, 48.23304866,
       69.33333363, 44.1734123 , 56.54967967, 41.81357945, 43.06758714,
       59.47872601, 55.96744634, 50.72584359, 50.18955371, 55.07008362,
       64.67120393, 51.55778   , 46.98162252, 47.70892847, 47.45980167,
       48.77045459, 30.92615938, 34.27629036, 23.99683956, 58.9505315 ])